/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package automato;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Lucas Samoyedem
 */
public class App extends javax.swing.JFrame {

    private Estado estadoAtual = null;
    private Estado estadoInicial = null;
    private boolean valido;
    private char ultimaLetraDigitada;
    private List<Estado> estadosAnteriores = new ArrayList<>();
    private Map<Character, Integer> letraxColuna = new HashMap<>();

    /**
     * Creates new form app
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tokens = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        montaAnalisador = new javax.swing.JButton();
        validador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokensActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite os tokens");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "δ", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "X", "Y", "Z"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setShowGrid(true);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(6).setResizable(false);
            table.getColumnModel().getColumn(7).setResizable(false);
            table.getColumnModel().getColumn(8).setResizable(false);
            table.getColumnModel().getColumn(9).setResizable(false);
            table.getColumnModel().getColumn(10).setResizable(false);
            table.getColumnModel().getColumn(11).setResizable(false);
            table.getColumnModel().getColumn(12).setResizable(false);
            table.getColumnModel().getColumn(13).setResizable(false);
            table.getColumnModel().getColumn(14).setResizable(false);
            table.getColumnModel().getColumn(15).setResizable(false);
            table.getColumnModel().getColumn(16).setResizable(false);
            table.getColumnModel().getColumn(17).setResizable(false);
            table.getColumnModel().getColumn(18).setResizable(false);
            table.getColumnModel().getColumn(19).setResizable(false);
            table.getColumnModel().getColumn(20).setResizable(false);
            table.getColumnModel().getColumn(21).setResizable(false);
            table.getColumnModel().getColumn(22).setResizable(false);
            table.getColumnModel().getColumn(23).setResizable(false);
            table.getColumnModel().getColumn(24).setResizable(false);
            table.getColumnModel().getColumn(25).setResizable(false);
        }

        montaAnalisador.setText("Montar analisador");
        montaAnalisador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montaAnalisadorActionPerformed(evt);
            }
        });

        validador.setEnabled(false);
        validador.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                validadorInputMethodTextChanged(evt);
            }
        });
        validador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validadorActionPerformed(evt);
            }
        });
        validador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                validadorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validadorKeyReleased(evt);
            }
        });

        jLabel2.setText("Validar tokens");

        mensagem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(validador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                            .addComponent(tokens, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(montaAnalisador, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1357, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tokens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(montaAnalisador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensagem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void montaAnalisadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montaAnalisadorActionPerformed
        String[] tokensArray = tokens.getText().split(" ");
        List<Estado> estados = new ArrayList<>();
        estadoInicial = new Estado(0, Character.MIN_VALUE);
        estadoInicial.setEstadoInical(true);
        estados.add(estadoInicial);
        int index = 1;
        for (String token : tokensArray) {
            Estado estadoAtualAux = estadoInicial;
            for (char c : token.toCharArray()) {
                Estado estadoAux = new Estado(index, c);
                estadoAtualAux.getProximosEstados().add(estadoAux);
                estadoAtualAux = estadoAux;
                estados.add(estadoAtualAux);
                index++;
            }
            estadoAtualAux.setEstadoFinal(true);
        }
        estadoAtual = estadoInicial;

        char letra = 'a';
        Integer coluna = 1;
        while (letra <= 'z') {
            letraxColuna.put(letra, coluna);
            coluna++;
            letra++;
        }

        int linha = 0;
        for (Estado estado : estados) {
            table.setValueAt(estado.getDescricaoEstado(), linha, 0);
            for (Estado proximoEstado : estado.getProximosEstados()) {
                Integer indexColuna = letraxColuna.get(proximoEstado.getLetra());
                table.setValueAt(proximoEstado.getDescricaoEstado(), linha, indexColuna);
            }
            linha++;
        }
        validador.setEnabled(true);
    }//GEN-LAST:event_montaAnalisadorActionPerformed

    private void tokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokensActionPerformed

    private void validadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validadorActionPerformed

    private void validadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validadorKeyPressed
        mensagem.setText(null);
        char token = evt.getKeyChar();
        if (token == '') {
            if (estadosAnteriores.isEmpty()) {
                estadoAtual = estadoInicial;
            } else {
                Estado estadoAtualAux = estadosAnteriores.get(estadosAnteriores.size() - 1);
                if (valido) {
                    estadosAnteriores.remove(estadoAtualAux);
                    estadoAtual = estadoAtualAux;
                    colorirLinha();
                } else {
                    token = validador.getText().charAt(validador.getText().length() - 2);
                }
            }
        }
        if (token == ' ') {
            if (estadoAtual.isEstadoFinal()) {
                mensagem.setText("Tolken Valido");
                mensagem.setForeground(Color.GREEN);
                estadoAtual = estadoInicial;
            } else {
                mensagem.setText("Tolken Invalido");
                mensagem.setForeground(Color.RED);
            }
            return;
        }
        Estado estadoSelecionado = estadoAtual.getProximoEstado(token);
        if (estadoSelecionado != null) {
            if (estadoAtual != null) {
                estadosAnteriores.add(estadoAtual);
            }
            estadoAtual = estadoSelecionado;
            valido = true;
            if (estadoAtual.isEstadoFinal()) {
                mensagem.setText("Tolken Valido");
                mensagem.setForeground(Color.GREEN);
            }
        } else {
            mensagem.setText("Tolken Invalido");
            mensagem.setForeground(Color.RED);
            valido = false;
        }
        colorirLinha();
    }//GEN-LAST:event_validadorKeyPressed

    private void colorirLinha() {
        table.updateUI();
        table.setShowGrid(true);
        final Color colorPadrao = table.getBackground();
        table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                setHorizontalAlignment(JLabel.CENTER);
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (row == estadoAtual.getNumero() - 1 && column == letraxColuna.get(estadoAtual.getLetra())) {
                    setBackground(Color.BLUE);
                } else {
                    setBackground(colorPadrao);
                }
                return c;
            }
        });
    }
    private void validadorInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_validadorInputMethodTextChanged
    }//GEN-LAST:event_validadorInputMethodTextChanged

    private void validadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validadorKeyReleased
    }//GEN-LAST:event_validadorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensagem;
    private javax.swing.JButton montaAnalisador;
    private javax.swing.JTable table;
    private javax.swing.JTextField tokens;
    private javax.swing.JTextField validador;
    // End of variables declaration//GEN-END:variables
}
